// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASj7EbtYv6t_vLChZyeFhT2DAjcsMvQ10',
    appId: '1:848485870372:web:81a36d73e311dbf656a1b1',
    messagingSenderId: '848485870372',
    projectId: 'study-app-cb328',
    authDomain: 'study-app-cb328.firebaseapp.com',
    storageBucket: 'study-app-cb328.appspot.com',
    measurementId: 'G-8GTX110HBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmriajgr4byCeJzT3SfQQIOeS42md-EqA',
    appId: '1:848485870372:android:bbc3172d9e2b3e2b56a1b1',
    messagingSenderId: '848485870372',
    projectId: 'study-app-cb328',
    storageBucket: 'study-app-cb328.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDigsmsVskf6UonT9UysSNTNDV91HifGaA',
    appId: '1:848485870372:ios:3edc26d19cff75bd56a1b1',
    messagingSenderId: '848485870372',
    projectId: 'study-app-cb328',
    storageBucket: 'study-app-cb328.appspot.com',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDigsmsVskf6UonT9UysSNTNDV91HifGaA',
    appId: '1:848485870372:ios:e8ec3241a76c8f0f56a1b1',
    messagingSenderId: '848485870372',
    projectId: 'study-app-cb328',
    storageBucket: 'study-app-cb328.appspot.com',
    iosBundleId: 'com.example.studyApp.RunnerTests',
  );
}
